command:
  - python
  - launcher.py
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
  - name: CLAIMOPS_SQL_WAREHOUSE_ID
    value: "26e842cddb906c23"
  - name: CLAIMOPS_SQL_HTTP_PATH
    value: "/sql/1.0/warehouses/26e842cddb906c23"
  - name: CLAIMOPS_GOLD_TABLE
    value: "healthcare.gold.claim_features"
  - name: CLAIMOPS_MODEL_NAME
    value: "healthcare.ml.claim_denial_model"
  - name: CLAIMOPS_MODEL_ALIAS
    value: "champion"
  - name: CLAIMOPS_VECTOR_INDEX_NAME
    value: "healthcare.gold.policy_chunks_index"
  - name: STREAMLIT_OIDC_ENABLED_PROVIDERS
    value: "google"
  - name: STREAMLIT_OIDC_GOOGLE_CLIENT_ID
    valueFrom: google_client_id
  - name: STREAMLIT_OIDC_GOOGLE_CLIENT_SECRET
    valueFrom: google_client_secret
  - name: STREAMLIT_OIDC_GOOGLE_REDIRECT_URI
    valueFrom: redirect_uri
  - name: STREAMLIT_OIDC_COOKIE_SECRET
    valueFrom: cookie_secret
  - name: CLAIMOPS_AUTH_MODE
    value: "auto"
