from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import pytest

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_CONTRACT_PATH = (
    _PROJECT_ROOT / "frontend" / "src" / "lib" / "contracts" / "claimops.ts"
)


@pytest.fixture(scope="module")
def python_feature_columns():
    from src.ml import FEATURE_COLUMNS

    return list(FEATURE_COLUMNS)


@pytest.fixture(scope="module")
def generated_ts_columns():
    assert _CONTRACT_PATH.exists(), f"Contract file not found: {_CONTRACT_PATH}"
    text = _CONTRACT_PATH.read_text(encoding="utf-8")
    match = re.search(
        r"export const FEATURE_COLUMNS: readonly string\[\] = \[(.*?)\]\s*as const;",
        text,
        re.DOTALL,
    )
    assert match, "Could not parse FEATURE_COLUMNS from generated file"
    columns = re.findall(r'"([^"]+)"', match.group(1))
    return columns


def test_contract_matches_python(python_feature_columns, generated_ts_columns):
    assert (
        generated_ts_columns == python_feature_columns
    ), "Frontend contract FEATURE_COLUMNS does not match src.ml.FEATURE_COLUMNS"


def test_contract_file_is_formatted(python_feature_columns, generated_ts_columns):
    text = _CONTRACT_PATH.read_text(encoding="utf-8")
    assert text.startswith(
        "// Auto-generated by tools/export_frontend_contracts.py"
    ), "File missing auto-generated header"
