resources:
  jobs:
    load_sample_data:
      name: "[${bundle.target}] Load Sample Data"
      job_clusters:
        - job_cluster_key: shared_cluster
          new_cluster:
            spark_version: ${var.spark_version}
            node_type_id: ${var.node_type_id}
            num_workers: 1
      tasks:
        - task_key: load_sample_data
          spark_python_task:
            python_file: ../../../../src/scripts/load_sample_data.py
            parameters:
              - --catalog
              - ${var.catalog}
              - --schema
              - ${var.bronze_schema}
              - --volume
              - raw_landing
              - --overwrite
          job_cluster_key: shared_cluster
