from __future__ import annotations

import sys
from pathlib import Path
from typing import Final

_TOOLS_ROOT: Final[Path] = Path(__file__).resolve().parent
_PROJECT_ROOT: Final[Path] = _TOOLS_ROOT.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.ml import FEATURE_COLUMNS  # noqa: E402

_TEMPLATE: Final[str] = """\
// Auto-generated by tools/export_frontend_contracts.py
// Do not edit manually. Regenerate when src.ml.FEATURE_COLUMNS changes.

export const FEATURE_COLUMNS: readonly string[] = {columns} as const;

export type ClaimFeatureRow = Record<(typeof FEATURE_COLUMNS)[number], number | null>;

export type FeatureColumn = (typeof FEATURE_COLUMNS)[number];
"""


def _format_columns(columns: tuple[str, ...]) -> str:
    items = ",\n  ".join(f'"{col}"' for col in columns)
    return f"[\n  {items},\n]"


def main() -> None:
    ts_content = _TEMPLATE.format(columns=_format_columns(FEATURE_COLUMNS))
    output_path = (
        _PROJECT_ROOT / "frontend" / "src" / "lib" / "contracts" / "claimops.ts"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ts_content, encoding="utf-8")
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
