from __future__ import annotations

from typing import Final


LOG_CATEGORY_PIPELINE_OPS: Final[str] = "pipeline_ops"
LOG_CATEGORY_DATA_QUALITY: Final[str] = "data_quality"
LOG_CATEGORY_GOVERNANCE_AUDIT: Final[str] = "governance_audit"
LOG_CATEGORY_ANALYTICS_BUILD: Final[str] = "analytics_build"
LOG_CATEGORY_SILVER_PIPELINE: Final[str] = "silver_pipeline"
LOG_CATEGORY_QUARANTINE_AUDIT: Final[str] = "quarantine_audit"
LOG_CATEGORY_POLICY_CHUNKING: Final[str] = "policy_chunking"
LOG_CATEGORY_GOLD_PIPELINE: Final[str] = "gold_pipeline"

LOG_CATEGORIES: Final[tuple[str, ...]] = (
    LOG_CATEGORY_PIPELINE_OPS,
    LOG_CATEGORY_DATA_QUALITY,
    LOG_CATEGORY_GOVERNANCE_AUDIT,
    LOG_CATEGORY_ANALYTICS_BUILD,
    LOG_CATEGORY_SILVER_PIPELINE,
    LOG_CATEGORY_QUARANTINE_AUDIT,
    LOG_CATEGORY_POLICY_CHUNKING,
    LOG_CATEGORY_GOLD_PIPELINE,
)


__all__ = [
    "LOG_CATEGORIES",
    "LOG_CATEGORY_ANALYTICS_BUILD",
    "LOG_CATEGORY_DATA_QUALITY",
    "LOG_CATEGORY_GOVERNANCE_AUDIT",
    "LOG_CATEGORY_PIPELINE_OPS",
    "LOG_CATEGORY_POLICY_CHUNKING",
    "LOG_CATEGORY_GOLD_PIPELINE",
    "LOG_CATEGORY_QUARANTINE_AUDIT",
    "LOG_CATEGORY_SILVER_PIPELINE",
]
