// Auto-generated by tools/export_frontend_contracts.py
// Do not edit manually. Regenerate when src.ml.FEATURE_COLUMNS changes.

export const FEATURE_COLUMNS: readonly string[] = [
  "is_procedure_missing",
  "is_amount_missing",
  "amount_to_benchmark_ratio",
  "billed_vs_avg_cost",
  "high_cost_flag",
  "severity_procedure_mismatch",
  "specialty_diagnosis_mismatch",
  "provider_location_missing",
  "diagnosis_severity_encoded",
  "diagnosis_count",
  "provider_claim_count",
  "provider_claim_count_30d",
  "provider_risk_score",
  "provider_claim_count_60d",
  "provider_claim_count_90d",
  "cost_overbenchmark_and_highseverity",
  "mismatch_and_overbenchmark",
  "provider_30d_denial_rate",
  "missing_fields_count",
  "low_volume_provider_risk",
  "dx_px_compatible",
  "dx_px_pair_risk_prior",
] as const;

export type ClaimFeatureRow = Record<(typeof FEATURE_COLUMNS)[number], number | null>;

export type FeatureColumn = (typeof FEATURE_COLUMNS)[number];
